/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_page;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import util.connectionUtil;

/**
 *
 * @author Murat Kaya
 */
public class main_agency_rates extends javax.swing.JFrame {

    /**
     * Creates new form main_agency_rates
     */
    
    static String username;
    
    public main_agency_rates(String uname) {
        username = uname;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        orderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel_previous = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idButton = new javax.swing.JRadioButton();
        nameButton = new javax.swing.JRadioButton();
        rateButton = new javax.swing.JRadioButton();

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Melbourne Real Estate Agencies");
        jTextField2.setBorder(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Remove Property");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(username);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Melbourne Real Estate Agencies");
        jTextField3.setBorder(null);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Rates of Agencies");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Agency Name", "Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTable2);
        try{
            String query = "SELECT agencies.Agency_ID,Agency_Name, AVG(Rate) FROM agencies JOIN serves ON agencies.Agency_ID=serves.Agency_ID"
            + "    GROUP BY  agencies.Agency_ID,agencies.Agency_Name ORDER BY agencies.Agency_ID ASC";
            PreparedStatement ps=connectionUtil.getTheConnection().prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                String id=String.valueOf(rs.getInt("agencies.Agency_ID"));
                String name=rs.getString("Agency_Name");
                String rate=String.valueOf(rs.getInt("AVG(Rate)"));

                String tbData[]={id,name,rate};
                DefaultTableModel tblModel=(DefaultTableModel)jTable2.getModel();
                tblModel.addRow(tbData);
            }

        } catch(SQLException e){
            System.out.println(e.getMessage());
        }

        jLabel_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_page/previous.png"))); // NOI18N
        jLabel_previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_previousMouseClicked(evt);
            }
        });

        jLabel1.setText("Order by: ");

        idButton.setText("ID");
        idButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idButtonActionPerformed(evt);
            }
        });

        nameButton.setText("Name");
        nameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameButtonActionPerformed(evt);
            }
        });

        rateButton.setText("Rate");
        rateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3)
            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(idButton)
                        .addGap(18, 18, 18)
                        .addComponent(nameButton)
                        .addGap(18, 18, 18)
                        .addComponent(rateButton)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idButton)
                    .addComponent(nameButton)
                    .addComponent(rateButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        orderGroup.add(idButton);
        idButton.setSelected(true);
        orderGroup.add(nameButton);
        orderGroup.add(rateButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel_previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousMouseClicked
        // TODO add your handling code here:
        main_agency main= new main_agency(username);
        main.pack(); 
        main.setLocationRelativeTo(null);        
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_previousMouseClicked

    private void idButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idButtonActionPerformed
        // TODO add your handling code here:
        try{
            String query = "SELECT agencies.Agency_ID,Agency_Name, AVG(Rate) FROM agencies JOIN serves ON agencies.Agency_ID=serves.Agency_ID"
                    + "    GROUP BY  agencies.Agency_ID,agencies.Agency_Name ORDER BY agencies.Agency_ID ASC";
            PreparedStatement ps=connectionUtil.getTheConnection().prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel tblModel=(DefaultTableModel)jTable2.getModel();
            tblModel.setRowCount(0);

            while(rs.next()){
                String id=String.valueOf(rs.getInt("agencies.Agency_ID"));
                String name=rs.getString("Agency_Name");
                String rate=String.valueOf(rs.getInt("AVG(Rate)"));
                
                String tbData[]={id,name,rate};
                tblModel.addRow(tbData);
            }

        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_idButtonActionPerformed

    private void rateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateButtonActionPerformed
        // TODO add your handling code here:
        try{
            String query = "SELECT agencies.Agency_ID,Agency_Name, AVG(Rate) FROM agencies JOIN serves ON agencies.Agency_ID=serves.Agency_ID"
                    + "    GROUP BY  agencies.Agency_ID,agencies.Agency_Name ORDER BY AVG(Rate) DESC";
            PreparedStatement ps=connectionUtil.getTheConnection().prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel tblModel=(DefaultTableModel)jTable2.getModel();
            tblModel.setRowCount(0);

            while(rs.next()){
                String id=String.valueOf(rs.getInt("agencies.Agency_ID"));
                String name=rs.getString("Agency_Name");
                String rate=String.valueOf(rs.getInt("AVG(Rate)"));
                
                String tbData[]={id,name,rate};
                tblModel.addRow(tbData);
            }

        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_rateButtonActionPerformed

    private void nameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameButtonActionPerformed
        // TODO add your handling code here:
        try{
            String query = "SELECT agencies.Agency_ID,Agency_Name, AVG(Rate) FROM agencies JOIN serves ON agencies.Agency_ID=serves.Agency_ID"
                    + "    GROUP BY  agencies.Agency_ID,agencies.Agency_Name ORDER BY agencies.Agency_Name ASC";
            PreparedStatement ps=connectionUtil.getTheConnection().prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel tblModel=(DefaultTableModel)jTable2.getModel();
            tblModel.setRowCount(0);

            while(rs.next()){
                String id=String.valueOf(rs.getInt("agencies.Agency_ID"));
                String name=rs.getString("Agency_Name");
                String rate=String.valueOf(rs.getInt("AVG(Rate)"));
                
                String tbData[]={id,name,rate};
                tblModel.addRow(tbData);
            }

        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_nameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_agency_rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_agency_rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_agency_rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_agency_rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_agency_rates(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton idButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_previous;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton nameButton;
    private javax.swing.ButtonGroup orderGroup;
    private javax.swing.JRadioButton rateButton;
    // End of variables declaration//GEN-END:variables
}
