/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_page;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.connectionUtil;

/**
 *
 * @author Murat Kaya
 */
public class main_agency_addHouse extends javax.swing.JFrame {

    /**
     * Creates new form main_agency_addHouse
     */
    
    static String username;
   
    public main_agency_addHouse(String uname) {
        username = uname;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_name2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_bath_num = new javax.swing.JTextField();
        typeCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_car_num = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        jTextField_region = new javax.swing.JTextField();
        jTextField_landsize = new javax.swing.JTextField();
        jTextField_year = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jTextField_room_num = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_previous = new javax.swing.JLabel();
        m2_field = new javax.swing.JTextField();
        m2_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_council = new javax.swing.JTextField();
        jTextField_suburb = new javax.swing.JTextField();
        jTextField_postcode = new javax.swing.JTextField();
        jTextField_distance = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");

        jTextField_name2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_name2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(username);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Melbourne Real Estate Agencies");
        jTextField2.setBorder(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Add New Property");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bathroom Number:");

        jTextField_bath_num.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_bath_num.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        typeCombo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        typeCombo.setForeground(new java.awt.Color(255, 255, 255));
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "h", "u", "t" }));
        typeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adress:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Car Number:");

        jTextField_car_num.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_car_num.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Landsize:");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Distance:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price:");

        Type.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setText("Building Year:");

        jTextField_region.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_region.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_landsize.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_landsize.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_year.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_year.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_address.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_address.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_room_num.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_room_num.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Room Number:");

        jTextField_price.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_price.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Type:");

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OKAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_page/previous.png"))); // NOI18N
        jLabel_previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_previousMouseClicked(evt);
            }
        });

        m2_field.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        m2_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        m2_label.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        m2_label.setForeground(new java.awt.Color(255, 255, 255));
        m2_label.setText("Garden m^2");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Suburb:");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Region Name:");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Council Area:");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Postcode:");

        jTextField_council.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_council.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_suburb.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_suburb.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_postcode.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_postcode.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField_distance.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jTextField_distance.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_bath_num, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_region, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_landsize, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_council, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_suburb, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(jTextField_room_num, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_car_num, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_price, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextField_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m2_field, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_room_num, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_bath_num, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_car_num, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_landsize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Type)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_region, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_council, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suburb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(m2_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m2_field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        // TODO add your handling code here:
        String selected = typeCombo.getSelectedItem().toString();
        
        if(selected.equals("h")){
            m2_label.setText("Garden m^2");
            m2_label.setVisible(true);
            m2_field.setVisible(true);
        } else if(selected.equals("t")){
            m2_label.setText("Terrace m^2");
            m2_label.setVisible(true);
            m2_field.setVisible(true);
        } else {
            m2_label.setVisible(false);
            m2_field.setVisible(false);
        }
    }//GEN-LAST:event_typeComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //opening sign_up page
        String Address=jTextField_address.getText();
        String RoomNum=jTextField_room_num.getText().trim();
        String BathNum=jTextField_bath_num.getText().trim();
        String CarNum=jTextField_car_num.getText().trim();
        String landSize=jTextField_landsize.getText().trim();
        String year=jTextField_year.getText().trim();
        String price=jTextField_price.getText().trim();
        String agency="";
        String type=typeCombo.getSelectedItem().toString().trim();
        String region=jTextField_region.getText();
        String council=jTextField_council.getText();
        String suburb=jTextField_suburb.getText();
        String postcode=jTextField_postcode.getText();
        String distance=jTextField_distance.getText();
        String locationID="";

        //String agencyName=
        String getAgency="SELECT Agency_ID FROM agencies WHERE Username=?";
        String checkLocation="SELECT Location_ID from house_locations WHERE RegionName=? AND CouncilArea=? AND Postcode=? AND Distance=? AND Suburb=?";
        PreparedStatement ps2;//for agency name
        PreparedStatement ps3;//for location
        int countCheck=0;
         
        String query="INSERT INTO `houses`(`Address`, `RoomNum`, `Type`, `Price`, `Seller_Agency`,`Bathroom_Num`, `Car_Num`,`Landsize`, `YearBuilt`, `Location_ID`,`User_ID`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement ps;
        ResultSet rs;
        try{
                countCheck++;
                ps2=connectionUtil.getTheConnection().prepareStatement(getAgency); 
                ps2.setString(1, username);
                rs=ps2.executeQuery(); 
                if(rs.next()){
                    countCheck++;
                    agency = rs.getString("Agency_ID");
                    ps3=connectionUtil.getTheConnection().prepareStatement(checkLocation); 
                    ps3.setString(1, region);
                    ps3.setString(2, council);
                    ps3.setString(3, postcode);
                    ps3.setString(4, distance);
                    ps3.setString(5, suburb);
                    rs=ps3.executeQuery(); 
                    if(rs.next()){
                         locationID=rs.getString("Location_ID");
                    } else {
                        String query_loc = "INSERT INTO `house_locations`(`Suburb`, `Distance`, `Postcode`, `CouncilArea`, `RegionName`) VALUES (?,?,?,?,?)";
                        PreparedStatement ps_loc;
                        ps_loc=connectionUtil.getTheConnection().prepareStatement(query_loc);
                        ps_loc.setString(1, suburb);
                        ps_loc.setString(2, distance);
                        ps_loc.setString(3, postcode);
                        ps_loc.setString(4, council);
                        ps_loc.setString(5, region);
                        int row = ps_loc.executeUpdate();
                        if(row!=1) JOptionPane.showMessageDialog(null, "Error adding location!");
                        
                        String q_locid = "SELECT MAX(location_id) AS id FROM house_locations";
                        PreparedStatement ps_locid;
                        ResultSet rs_locid;
                        ps_locid=connectionUtil.getTheConnection().prepareStatement(q_locid);
                        rs_locid=ps_locid.executeQuery();
                        rs_locid.next();
                        locationID=rs_locid.getString("id");
                    }
                         try {
                            ps=connectionUtil.getTheConnection().prepareStatement(query);
                            //ps.setString(1, "31");
                            ps.setString(1, Address);
                            ps.setString(2, RoomNum);
                            ps.setString(3,type);
                            ps.setString(4,price);
                            ps.setString(5,agency);
                            ps.setString(6,BathNum);
                            ps.setString(7,CarNum);
                            ps.setString(8,landSize);
                            ps.setString(9,year);
                            ps.setString(10,locationID);
                            ps.setString(11,"0");                 

                            int rowCount=ps.executeUpdate();
                            
                            String query_id = "SELECT MAX(House_ID) AS id FROM HOUSES";
                            PreparedStatement ps_id;
                            ResultSet rs_id;
                            
                            ps_id=connectionUtil.getTheConnection().prepareStatement(query_id);
                            rs_id=ps_id.executeQuery();
                            rs_id.next();
                            String houseID = rs_id.getString("id");
                            
                            String query_sub="";
                            PreparedStatement ps_sub;
                            if(type.equals("h")){
                                String garden_m2 = m2_field.getText();
                                query_sub="INSERT INTO `villas_wc`(`House_ID`, `Garden_m2`) VALUES (?,?)";
                                ps_sub=connectionUtil.getTheConnection().prepareStatement(query_sub);
                                ps_sub.setString(1, houseID);
                                ps_sub.setString(2, garden_m2);
                            } else if(type.equals("t")){
                                String terrace_m2 = m2_field.getText();
                                query_sub="INSERT INTO `terrace_wc`(`House_ID`, `Terrace_m2`) VALUES (?,?)";
                                ps_sub=connectionUtil.getTheConnection().prepareStatement(query_sub);
                                ps_sub.setString(1, houseID);
                                ps_sub.setString(2, terrace_m2);
                            } else {
                                query_sub="INSERT INTO `units`(`House_ID`) VALUES (?)";
                                ps_sub=connectionUtil.getTheConnection().prepareStatement(query_sub);
                                ps_sub.setString(1, houseID);
                            }
                            int rowCount2=ps_sub.executeUpdate();
                            
                            if(rowCount==1 && rowCount2==1){
                                JOptionPane.showMessageDialog(null, "New house has been successfully created.");
                                this.dispose();
                                main_agency main= new main_agency(username);
                                main.setVisible(true);
                                main.setExtendedState(NORMAL);

                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(main_agency_addHouse.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(main_agency_addHouse.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(countCheck!=2){
             JOptionPane.showMessageDialog(null, "Please check your Owner ID or Agency Name and try again.");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel_previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousMouseClicked
        // TODO add your handling code here:
        main_agency main= new main_agency(username);        
        main.pack(); 
        main.setLocationRelativeTo(null);        
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_previousMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_agency_addHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_agency_addHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_agency_addHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_agency_addHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_agency_addHouse(username).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_previous;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_bath_num;
    private javax.swing.JTextField jTextField_car_num;
    private javax.swing.JTextField jTextField_council;
    private javax.swing.JTextField jTextField_distance;
    private javax.swing.JTextField jTextField_landsize;
    private javax.swing.JTextField jTextField_name2;
    private javax.swing.JTextField jTextField_postcode;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_region;
    private javax.swing.JTextField jTextField_room_num;
    private javax.swing.JTextField jTextField_suburb;
    private javax.swing.JTextField jTextField_year;
    private javax.swing.JTextField m2_field;
    private javax.swing.JLabel m2_label;
    private javax.swing.JComboBox<String> typeCombo;
    // End of variables declaration//GEN-END:variables
}
